apiVersion: v1
kind: Pod
metadata:
  name: test
  labels:
    app.kubernetes.io/name: speedtest
    app.kubernetes.io/created-by: bcorder
spec:
  containers:
    - name: speedtest
      image: henrywhitaker3/speedtest-tracker:latest
      volumeMounts:
        - name: nfs-volume
          mountPath: /config
  volumes:
    - name: nfs-volume
      nfs:
        server: nas.corder.local
        path: /mnt/Goliath2/containers/speedtest
        readOnly: no