- hosts: "*"
  become: yes
  gather_facts: true
  tasks:

  ### Update/upgrade all packages

    - name: Upgrade all packages - dnf
      ansible.builtin.dnf:
        name: "*"
        state: latest
      when:
        - ansible_os_family == "RedHat"

    - name: Upgrade all packages - apt
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist
      when: ansible_os_family == "Debian"

  
  ### Check for reboot required; reboot if required

    - name: Check if a reboot is required.
      ansible.builtin.stat:
        path: /var/run/reboot-required
        get_md5: no
      register: reboot_required_file

    - name: Reboot the server (if required).
      ansible.builtin.reboot:
      when: reboot_required_file.stat.exists == true

  ### Remove dependencies that are no longer required

    - name: Remove dependencies that are no longer required (dnf)
      ansible.builtin.dnf:
        autoremove: yes
      when: ansible_os_family == "RedHat"

    - name: Remove dependencies that are no longer required (apt)
      ansible.builtin.apt:
        autoremove: yes
      when: ansible_os_family == "Debian"