- hosts: "loadbalancers"
  become: yes
  gather_facts: true
  serial: 1
  tasks:

  

  - name: Install HAproxy, keepalived, utils
    ansible.builtin.apt:
      pkg:
      - haproxy
      - keepalived
      - curl
      update_cache: yes
      
  - name: Copy HAproxy config to service location
    ansible.builtin.copy:
      src: "../../../configs/{{ inventory_hostname }}/haproxy.cfg"
      dest: /etc/haproxy/haproxy.cfg
      backup: true
      validate: sudo haproxy -f %s -c

  - name: Copy keepalived config to service location
    ansible.builtin.copy:
      src: "../../../configs/{{ inventory_hostname }}/keepalived.conf"
      dest: /etc/keepalived/keepalived.conf
      backup: true
      validate: sudo keepalived -t %s

  - name: Restart service haproxy
    ansible.builtin.service:
      name: haproxy
      state: restarted

  - name: Restart service keepalived
    ansible.builtin.service:
      name: keepalived
      state: restarted

  - name: Install CrowdSec repos
    ansible.builtin.shell: curl -s https://install.crowdsec.net | sudo sh
    args:
      executable: /bin/bash

  - name: Install CrowdSec
    ansible.builtin.apt:
      pkg:
      - crowdsec
      - crowdsec-firewall-bouncer-iptables
      update_cache: yes

  - name: Enroll CrowdSec console with UI
    ansible.builtin.shell: "sudo cscli console enroll -e context {{ lookup('ansible.builtin.env', 'CROWDSEC_ENROLLMENT_KEY') }}"