- hosts: "loadbalancers"
  become: yes
  gather_facts: true
  serial: 1
  tasks:

  - name: Install CrowdSec repos
    ansible.builtin.command: "curl -s https://install.crowdsec.net | sudo sh"

  - name: Install HAproxy, keepalived, crowdsec
    ansible.builtin.apt:
      pkg:
      - haproxy
      - keepalived
      - crowdsec
      - crowdsec-firewall-bouncer-iptables
      update_cache: yes
      
  - name: Copy HAproxy config to service location
    ansible.builtin.copy:
      src: "../../../configs/{{ inventory_hostname }}/haproxy.cfg"
      dest: /etc/haproxy/haproxy.cfg
      backup: true
      validate: sudo haproxy -f %s -c

  - name: Copy keepalived config to service location
    ansible.builtin.copy:
      src: "../../../configs/{{ inventory_hostname }}/keepalived.conf"
      dest: /etc/keepalived/keepalived.conf
      backup: true
      validate: sudo keepalived -t %s

  - name: Restart service haproxy
    ansible.builtin.service:
      name: haproxy
      state: restarted

  - name: Restart service keepalived
    ansible.builtin.service:
      name: keepalived
      state: restarted

  - name: Enroll CrowdSec console with UI
    ansible.builtin.command: "sudo cscli console enroll -e context $CROWDSEC_ENROLLMENT_KEY"