- hosts: "loadbalancers"
  become: yes
  gather_facts: true
  tasks:

  - name: Install HAproxy and keepalived
    ansible.builtin.apt:
      pkg:
      - haproxy
      - keepalived
      update_cache: yes
      
  - name: Copy HAproxy config to service location
    ansible.builtin.copy:
      src: "../../../configs/{{ inventory_hostname }}/haproxy.cfg"
      dest: /etc/haproxy/haproxy.cfg
      force: true
      backup: true
      validate: sudo haproxy -f %s -c

  - name: Copy keepalived config to service location
    ansible.builtin.copy:
      src: "../../../configs/{{ inventory_hostname }}/keepalived.conf"
      dest: /etc/keepalived/keepalived.conf
      force: true
      backup: true
      validate: sudo keepalived -t %s

  - name: Restart service haproxy
    ansible.builtin.service:
      name: haproxy
      state: restarted

  - name: Restart service keepalived
    ansible.builtin.service:
      name: keepalived
      state: restarted